// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjWZwcmpx-amcvwO6S5vF4SDDTh3qRcF4',
    appId: '1:965164667454:web:7a1595ab04a82c8dd7b76f',
    messagingSenderId: '965164667454',
    projectId: 'app-bascosta',
    authDomain: 'app-bascosta.firebaseapp.com',
    storageBucket: 'app-bascosta.firebasestorage.app',
    measurementId: 'G-84KWKLDY5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADM7S2QSM3Mp-4ZneROcp2-asBrMYdn3Q',
    appId: '1:965164667454:android:08bda4ad9f70443ed7b76f',
    messagingSenderId: '965164667454',
    projectId: 'app-bascosta',
    storageBucket: 'app-bascosta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3c84dse8vwLWHDjt2tTiL_QIocPtnYWM',
    appId: '1:965164667454:ios:0397407fae9d9bddd7b76f',
    messagingSenderId: '965164667454',
    projectId: 'app-bascosta',
    storageBucket: 'app-bascosta.firebasestorage.app',
    iosBundleId: 'com.example.pruebasFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3c84dse8vwLWHDjt2tTiL_QIocPtnYWM',
    appId: '1:965164667454:ios:0397407fae9d9bddd7b76f',
    messagingSenderId: '965164667454',
    projectId: 'app-bascosta',
    storageBucket: 'app-bascosta.firebasestorage.app',
    iosBundleId: 'com.example.pruebasFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjWZwcmpx-amcvwO6S5vF4SDDTh3qRcF4',
    appId: '1:965164667454:web:7835ed390bceb5d9d7b76f',
    messagingSenderId: '965164667454',
    projectId: 'app-bascosta',
    authDomain: 'app-bascosta.firebaseapp.com',
    storageBucket: 'app-bascosta.firebasestorage.app',
    measurementId: 'G-000PMNY1VX',
  );

}