<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.ble_devices_app">

    <!-- Android 12+ permisos BLE -->
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />

    <!-- Pre-Android 12 (necesario para compatibilidad en algunos OEMs) -->
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

    <!-- minSdk 21+ requerido por flutter_reactive_ble -->
    <uses-sdk android:minSdkVersion="21" />

    <application
        android:label="BLE Devices"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">

        <!-- Declarar que haremos escaneo BLE (queries opcionales) -->
        <queries>
            <intent>
                <action android:name="android.bluetooth.adapter.action.REQUEST_ENABLE"/>
            </intent>
        </queries>

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

    </application>
</manifest>

