name: pruebas_flutter
description: "App Flutter BLE"
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  flutter_bluetooth_serial: ^0.4.0
  flutter_reactive_ble: ^5.3.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

